name: CordCloud

on:
  schedule:
    - cron: "20 2 * * *"
  workflow_dispatch:

jobs:
  checkin:
    runs-on: ubuntu-latest
    steps:
      - name: Random Delay
        shell: bash
        run: |
          delay=$(( RANDOM % 600 ))
          echo "sleep ${delay}s"
          sleep "$delay"

      - uses: actions/checkout@v4
      - uses: ./
        with:
          email: ${{ secrets.CC_EMAIL }}
          passwd: ${{ secrets.CC_PASSWD }}
          secret: ${{ secrets.CC_SECRET }}
          verify_method: ga
          host: cordcloud.one
          trust_device: false
          telegram_bot_token: ${{ secrets.TG_BOT_TOKEN }}
          telegram_chat_id: ${{ secrets.TG_CHAT_ID }}
